spring:
  application:
    name: EurekaServerHigh
  profiles: peer2

server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://user:123@peer1:8761/eureka/,http://user:123@peer3:8763/eureka/
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123